replicaCount: 1

image:
  repository: nginx
  tag: "1.25.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true   # Enable ingress
  className: "gce"  # Use GCP HTTP(S) Load Balancer
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "microservice-ip"  # NAME of your reserved static IP in GCP
  hosts:
    - host: "34.61.5.89.nip.io"
      paths:
        - path: /
          pathType: Prefix
  tls: []
