apiVersion: v1
kind: Service
metadata:
  name: microservice-microservice
spec:
  type: LoadBalancer
  loadBalancerIP: 34.61.5.89  # Optional: only if you reserved a static IP in GCP
  selector:
    app: microservice
  ports:
    - port: 80
      targetPort: 80
