replicaCount: 3

image:
  repository: python
  tag: "3.11"
  pullPolicy: IfNotPresent

command: ["python", "-m", "http.server", "80"]

service:
  port: 80

ingress:
  enabled: true
  className: nginx
  hostname: "" # workflow will inject nip.io hostname
  path: /
