service:
  type: ClusterIP  # ✅ Required for GKE Ingress

ingress:
  enabled: true    # ✅ Enable Ingress
  className: gce   # ✅ For GKE, "gce" is valid
  annotations:
    kubernetes.io/ingress.global-static-ip-name: gke-static-ip  # ✅ Binds Ingress to your reserved static IP
  hosts:
    - host: 34.61.5.89.nip.io  # ✅ nip.io maps to your static IP
      paths:
        - path: /
          pathType: Prefix

