replicaCount: 1

image:
  repository: nginx
  tag: "1.25.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: 34.123.45.67.nip.io
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: microservice
              port:
                number: 80

