replicaCount: 1

image:
  repository: nginx
  tag: "1.25.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  staticIP: "34.61.5.89" # replace with your GCP static IP
  path: /
  pathType: Prefix

resources: {}
