replicaCount: 1

image:
  repository: nginx
  tag: "1.25.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: gce
  annotations:
    kubernetes.io/ingress.global-static-ip-name: gke-static-ip
  hosts:
    - host: 34.61.5.89.nip.io
      paths:
        - path: /
          pathType: Prefix
