replicaCount: 2

image:
  repository: nginx
  tag: "1.21.6"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: myapp.34.120.50.10.nip.io  # Replace with your ingress external IP + nip.io
      paths:
        - path: /
          pathType: Prefix
  tls: []  # Example: - secretName: tls-secret
