replicaCount: 1

image:
  repository: nginx
  tag: "1.25.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: "34.61.5.89.nip.io"   # Replace with your static IP + .nip.io
      paths:
        - path: /
          pathType: Prefix
  tls: []

