replicaCount: 1

image:
  repository: nginx
  tag: "1.25.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: "34.10.246.130.nip.io"
  annotations: {}
  tls:
    enabled: true
    clusterIssuer: letsencrypt-prod
    secretName: microservice-tls

                number: 80

