containers:
  - name: {{ .Chart.Name }}
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    {{- if .Values.command }}
    command: {{ toJson .Values.command }}
    {{- end }}
    ports:
      - containerPort: {{ .Values.service.port }}
