name: Deploy Nginx to GKE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Authenticate to GCP
      - name: Set up GCP authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Get GKE cluster credentials
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_ZONE }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Step 4: Get static IP from GCP
      - name: Get static IP address
        id: get-ip
        run: |
          IP=$(gcloud compute addresses describe ${{ secrets.GKE_STATIC_IP_NAME }} \
            --region=${{ secrets.GKE_STATIC_IP_REGION }} \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --format='value(address)')
          echo "STATIC_IP=$IP" >> $GITHUB_ENV

      # Step 5: Install Helm
      - name: Set up Helm
        uses: azure/setup-helm@v4

      # Step 6: Deploy Helm chart with static IP + nip.io
      - name: Deploy Nginx via Helm
        run: |
          helm upgrade --install mynginx ./nginx-staticip \
            --set service.loadBalancerIP=${{ env.STATIC_IP }} \
            --set ingress.hosts[0].host=${{ env.STATIC_IP }}.nip.io \
            --set ingress.hosts[0].paths[0].path="/" \
            --set ingress.hosts[0].paths[0].pathType=ImplementationSpecific

      # Step 7: Output URL
      - name: Show Nginx URL
        run: echo "Nginx available at http://${{ env.STATIC_IP }}.nip.io"
