name: GKE Microservice Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: able-armor-468408-v6     # 🔹 Replace with your GCP project ID
  GKE_CLUSTER: my-private-cluster      # 🔹 Replace with your cluster name
  GKE_ZONE: asia-south1-a               # 🔹 Replace with your cluster location
  HELM_RELEASE: microservice
  HELM_CHART_PATH: ./helm/microservice
  TF_DIR: ./terraform

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Authenticate with GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3️⃣ Set gcloud project
      - name: Set GCP Project
        run: gcloud config set project $PROJECT_ID

      # 4️⃣ Terraform Init & Apply
      - name: Terraform Init
        run: |
          cd $TF_DIR
          terraform init

      - name: Terraform Apply
        run: |
          cd $TF_DIR
          terraform apply -auto-approve

      # 5️⃣ Connect to GKE
      - name: Get GKE Credentials
        run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

      # 6️⃣ Install Helm
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      # 7️⃣ Deploy via Helm
      - name: Deploy Helm Chart
        run: |
          helm upgrade --install $HELM_RELEASE $HELM_CHART_PATH -f $HELM_CHART_PATH/values.yaml

      # 8️⃣ Verify Ingress
      - name: Check Ingress
        run: kubectl get ingress -A

