name: Deploy Microservice to GKE

on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  CLUSTER_ZONE: ${{ secrets.GKE_CLUSTER_ZONE }}
  STATIC_IP_REGION: ${{ secrets.GKE_STATIC_IP_REGION }}
  STATIC_IP_NAME: ${{ secrets.GKE_STATIC_IP_NAME }}
  RELEASE_NAME: microservice
  NAMESPACE: default

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Install GKE gcloud auth plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin --quiet
        echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

    - name: Get GKE Credentials
      run: |
        gcloud container clusters get-credentials $CLUSTER_NAME \
          --zone $CLUSTER_ZONE \
          --project $PROJECT_ID

    - name: Install GKE Ingress Controller (GCE)
      run: |
        kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-gce/main/deploy/static/mandatory.yaml
        echo "Waiting for GCE ingress controller..."
        kubectl wait deployment l7-default-backend -n kube-system --for=condition=available --timeout=180s || true

    - name: Wait for Static IP to be Reserved
      run: |
        IP=$(gcloud compute addresses describe $STATIC_IP_NAME \
          --region $STATIC_IP_REGION \
          --format="value(address)")
        if [ -z "$IP" ]; then
          echo "❌ ERROR: Static IP not found in region $STATIC_IP_REGION"
          exit 1
        fi
        echo "✅ Static IP: $IP"
        echo "STATIC_IP=$IP" >> $GITHUB_ENV

    - name: Deploy Microservice with Helm
      run: |
        helm upgrade --install $RELEASE_NAME ./helm/microservice \
          -f ./helm/microservice/values.yaml \
          --namespace $NAMESPACE --create-namespace
