name: Deploy Microservice to GKE

on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  CLUSTER_ZONE: ${{ secrets.GKE_CLUSTER_ZONE }}         # e.g., us-central1-a
  STATIC_IP_REGION: ${{ secrets.GKE_STATIC_IP_REGION }} # e.g., us-central1
  STATIC_IP_NAME: ${{ secrets.GKE_STATIC_IP_NAME }}
  RELEASE_NAME: microservice
  NAMESPACE: default

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Install GKE gcloud auth plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin --quiet
        echo "export USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

    - name: Get GKE Credentials
      run: |
        gcloud container clusters get-credentials $CLUSTER_NAME \
          --zone $CLUSTER_ZONE \
          --project $PROJECT_ID

    - name: Get Static IP Address
      id: get-ip
      run: |
        IP_ADDRESS=$(gcloud compute addresses describe $STATIC_IP_NAME \
          --region $STATIC_IP_REGION \
          --format="value(address)")
        echo "STATIC_IP=$IP_ADDRESS" >> $GITHUB_ENV
        echo "Using Static IP: $IP_ADDRESS"

    - name: Install Helm
      uses: azure/setup-helm@v4

    - name: Deploy Microservice via Helm
      run: |
        helm upgrade --install $RELEASE_NAME ./helm/microservice \
          --namespace $NAMESPACE \
          --create-namespace \
          --set ingress.enabled=true \
          --set ingress.className=nginx \
          --set ingress.annotations."kubernetes\.io/ingress\.global-static-ip-name"=$STATIC_IP_NAME \
          --set ingress.hosts[0].host=${STATIC_IP}.nip.io

