name: Deploy NGINX to GKE with Static IP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set GCP Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      # Connect to GKE
      - name: Get GKE credentials
        run: gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }}

      # Install Helm
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      # Deploy with Helm using static IP
      - name: Deploy NGINX with Static IP
        run: |
          helm upgrade --install mynginx ./nginx-staticip \
            --set ingress.enabled=true \
            --set ingress.className=gce \
            --set ingress.annotations."kubernetes\.io/ingress\.global-static-ip-name"=${{ secrets.GKE_STATIC_IP_NAME }}

      # Verify Ingress
      - name: Verify Ingress IP
        run: |
          echo "Waiting for NGINX deployment to be ready..."
          kubectl wait --for=condition=available --timeout=300s deployment/mynginx
          kubectl get ingress

      # Show reserved static IP from GCP
      - name: Show Reserved Static IP
        run: |
          echo "Fetching reserved static IP from GCP..."
          STATIC_IP=$(gcloud compute addresses describe ${{ secrets.GKE_STATIC_IP_NAME }} --region=${{ secrets.GKE_STATIC_IP_REGION }} --format="get(address)")
          echo "✅ Your NGINX is available at: http://$STATIC_IP"
